"""
Configuration module for the backend application.
"""

from .settings import Settings, get_settings, settings
from .constants import (
    # AWS — DynamoDB Tables
    DYNAMODB_TABLE_ARTICLES_DEV,
    DYNAMODB_TABLE_ARTICLES_PROD,
    DYNAMODB_TABLE_PERSONAL_DEV,
    DYNAMODB_TABLE_PODCAST_DEV,
    # AWS — S3
    S3_ARTICLE_BODY_BUCKET_DEV,
    S3_ARTICLE_BODY_PREFIX,
    S3_BODY_FIELDS,
    S3_AUDIO_BUCKET_DEV,
    # AWS — Regions
    AWS_REGION_DEFAULT,
    AWS_REGION_S3,
    # AWS — GSI
    GSI_CATEGORY_DATE,
    GSI_SLUG,
    # AI Models
    BEDROCK_MODEL_ID_DEFAULT,
    BEDROCK_MODEL_ID_HAIKU,
    BEDROCK_MODEL_ID_SONNET,
    BEDROCK_MODEL_ID_NOVA,
    BEDROCK_MODEL_ID_NOVA_LITE,
    BEDROCK_MODEL_ID_NOVA_PRO,
    BEDROCK_EMBEDDING_MODEL_ID,
    BEDROCK_EMBEDDING_DIMENSION,
    BEDROCK_EMBEDDING_MAX_TOKENS,
    EMBEDDING_CHARS_PER_CHUNK,
    BEDROCK_REGION,
    # OpenSearch
    OPENSEARCH_INDEX_DEFAULT,
    # Timeouts
    HTTP_TIMEOUT_SHORT,
    HTTP_TIMEOUT_MEDIUM,
    HTTP_TIMEOUT_LONG,
    HTTP_TIMEOUT_SCRAPER,
    # Cache
    CACHE_TTL_DEFAULT,
    CACHE_TTL_VIDEO_SCHEDULES,
    REDIS_SOCKET_TIMEOUT,
    # URLs
    FRONTEND_URL_DEFAULT,
    BIGKINDS_API_URL_DEFAULT,
    ANTHROPIC_API_URL,
    NAVER_TV_URL_DEFAULT,
    # Categories
    CATEGORIES_KOREAN,
    ALL_CATEGORIES,
    CATEGORY_ENGLISH_TO_KOREAN,
    CATEGORY_KOREAN_TO_ENGLISH,
    VALID_CATEGORIES_ENGLISH,
    CATEGORY_SEARCH_ALIASES,
    # Pagination
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    BATCH_SIZE_DYNAMODB,
    # MBTI
    MBTI_GROUPS,
    MBTI_GROUP_INFO,
    # Podcast
    POLLY_MAX_CHARS,
    PODCAST_MAX_SCRIPT_LENGTH,
    PODCAST_VOICE_STYLES,
    # Item Types
    ITEM_TYPE_ARTICLE,
    ITEM_TYPE_SETTINGS,
    ITEM_TYPE_COLLECTION_LOG,
    ITEM_TYPE_ARTICLE_VERSION,
    ITEM_TYPE_USER_PROFILE,
    ITEM_TYPE_ARCHIVED_SENTENCE,
    ITEM_TYPE_READING_RECORD,
    ITEM_TYPE_PODCAST,
    # CORS
    CORS_HEADERS,
)

__all__ = [
    # Settings
    'Settings',
    'get_settings',
    'settings',
    # AWS — DynamoDB Tables
    'DYNAMODB_TABLE_ARTICLES_DEV',
    'DYNAMODB_TABLE_ARTICLES_PROD',
    'DYNAMODB_TABLE_PERSONAL_DEV',
    'DYNAMODB_TABLE_PODCAST_DEV',
    # AWS — S3
    'S3_ARTICLE_BODY_BUCKET_DEV',
    'S3_ARTICLE_BODY_PREFIX',
    'S3_BODY_FIELDS',
    'S3_AUDIO_BUCKET_DEV',
    # AWS — Regions
    'AWS_REGION_DEFAULT',
    'AWS_REGION_S3',
    # AWS — GSI
    'GSI_CATEGORY_DATE',
    'GSI_SLUG',
    # AI Models
    'BEDROCK_MODEL_ID_DEFAULT',
    'BEDROCK_MODEL_ID_HAIKU',
    'BEDROCK_MODEL_ID_SONNET',
    'BEDROCK_MODEL_ID_NOVA',
    'BEDROCK_MODEL_ID_NOVA_LITE',
    'BEDROCK_MODEL_ID_NOVA_PRO',
    'BEDROCK_EMBEDDING_MODEL_ID',
    'BEDROCK_EMBEDDING_DIMENSION',
    'BEDROCK_EMBEDDING_MAX_TOKENS',
    'EMBEDDING_CHARS_PER_CHUNK',
    'BEDROCK_REGION',
    # OpenSearch
    'OPENSEARCH_INDEX_DEFAULT',
    # Timeouts
    'HTTP_TIMEOUT_SHORT',
    'HTTP_TIMEOUT_MEDIUM',
    'HTTP_TIMEOUT_LONG',
    'HTTP_TIMEOUT_SCRAPER',
    # Cache
    'CACHE_TTL_DEFAULT',
    'CACHE_TTL_VIDEO_SCHEDULES',
    'REDIS_SOCKET_TIMEOUT',
    # URLs
    'FRONTEND_URL_DEFAULT',
    'BIGKINDS_API_URL_DEFAULT',
    'ANTHROPIC_API_URL',
    'NAVER_TV_URL_DEFAULT',
    # Categories
    'CATEGORIES_KOREAN',
    'ALL_CATEGORIES',
    'CATEGORY_ENGLISH_TO_KOREAN',
    'CATEGORY_KOREAN_TO_ENGLISH',
    'VALID_CATEGORIES_ENGLISH',
    'CATEGORY_SEARCH_ALIASES',
    # Pagination
    'DEFAULT_PAGE_SIZE',
    'MAX_PAGE_SIZE',
    'BATCH_SIZE_DYNAMODB',
    # MBTI
    'MBTI_GROUPS',
    'MBTI_GROUP_INFO',
    # Podcast
    'POLLY_MAX_CHARS',
    'PODCAST_MAX_SCRIPT_LENGTH',
    'PODCAST_VOICE_STYLES',
    # Item Types
    'ITEM_TYPE_ARTICLE',
    'ITEM_TYPE_SETTINGS',
    'ITEM_TYPE_COLLECTION_LOG',
    'ITEM_TYPE_ARTICLE_VERSION',
    'ITEM_TYPE_USER_PROFILE',
    'ITEM_TYPE_ARCHIVED_SENTENCE',
    'ITEM_TYPE_READING_RECORD',
    'ITEM_TYPE_PODCAST',
    # CORS
    'CORS_HEADERS',
]
